### ISSUE TITLE
NULL-deref in `get_active_class_name`

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#115]
Courtesy of @fr33tux

```nasm
(gdb) bt
#0  0x00005622b7095e2f in get_active_class_name ()
#1  0x00007f8348e3ddf9 in get_complete_function_path (execute_data=0x7f834ea1c340) at /root/snuffleupagus/src/sp_disabled_functions.c:19
#2  0x00007f8348e3eb56 in should_drop_on_ret (return_value=0x7ffe55f831d0, execute_data=0x7f834ea1c340) at /root/snuffleupagus/src/sp_disabled_functions.c:347
#3  0x00007f8348e3f4f8 in sp_execute_ex (execute_data=0x7f834ea1c340) at /root/snuffleupagus/src/sp_execute.c:87
#4  0x00005622b7096b0e in zend_call_function ()
#5  0x00005622b70c4296 in zend_call_method ()
#6  0x00005622b70df14a in ?? ()
#7  0x00005622b710ba70 in ?? ()
#8  0x00005622b711a1c4 in ?? ()
#9  0x00005622b70e6fdb in execute_ex ()
#10 0x00007f8348e3f4e1 in sp_execute_ex (execute_data=0x7f834ea1c280) at /root/snuffleupagus/src/sp_execute.c:85
#11 0x00005622b712c52c in ?? ()
#12 0x00005622b70e6fdb in execute_ex ()
#13 0x00007f8348e3f4e1 in sp_execute_ex (execute_data=0x7f834ea1c1e0) at /root/snuffleupagus/src/sp_execute.c:85
#14 0x00005622b712c52c in ?? ()
#15 0x00005622b70e6fdb in execute_ex ()
#16 0x00007f8348e3f4e1 in sp_execute_ex (execute_data=0x7f834ea1c150) at /root/snuffleupagus/src/sp_execute.c:85
#17 0x00005622b712c52c in ?? ()
#18 0x00005622b70e6fdb in execute_ex ()
#19 0x00007f8348e3f4e1 in sp_execute_ex (execute_data=0x7f834ea1c0a0) at /root/snuffleupagus/src/sp_execute.c:85
#20 0x00005622b7138bac in ?? ()
#21 0x00005622b70e6fdb in execute_ex ()
#22 0x00007f8348e3f4e1 in sp_execute_ex (execute_data=0x7f834ea1c030) at /root/snuffleupagus/src/sp_execute.c:85
#23 0x00005622b713bab7 in zend_execute ()
#24 0x00005622b70a61b2 in zend_execute_scripts ()
#25 0x00005622b7045da0 in php_execute_script ()
#26 0x00005622b6f24976 in main ()
(gdb) p *executor_globals->current_execute_data
$20 = {
  opline = 0x0, 
  call = 0x0, 
  return_value = 0x0, 
  func = 0x0, 
  This = {
    value = {
      lval = 140201937105280, 
      dval = 6.9268960604113991e-310, 
      counted = 0x7f834ea87180, 
      str = 0x7f834ea87180, 
      arr = 0x7f834ea87180, 
      obj = 0x7f834ea87180, 
      res = 0x7f834ea87180, 
      ref = 0x7f834ea87180, 
      ast = 0x7f834ea87180, 
      zv = 0x7f834ea87180, 
      ptr = 0x7f834ea87180, 
      ce = 0x7f834ea87180, 
      func = 0x7f834ea87180, 
      ww = {
        w1 = 1319661952, 
        w2 = 32643
      }
    }, 
    u1 = {
      v = {
        type = 8 '\b', 
        type_flags = 12 '\f', 
        const_flags = 0 '\000', 
        reserved = 2 '\002'
      }, 
      type_info = 33557512
    }, 
    u2 = {
      var_flags = 1, 
      next = 1, 
      cache_slot = 1, 
      lineno = 1, 
      num_args = 1, 
      fe_pos = 1, 
      fe_iter_idx = 1
    }
  }, 
  called_scope = 0x7f834ea7ff80, 
  prev_execute_data = 0x7f834ea1c280, 
  symbol_table = 0x7f834ea082a0, 
  run_time_cache = 0x7f834ea81c90, 
  literals = 0x7f83457c3d78
}
(gdb) i r
rax            0x7ffe55f83110	140730340749584
rbx            0x0	0
rcx            0x7ffe55f831d0	140730340749776
rdx            0x0	0
rsi            0x7f834ea1c340	140201936667456
rdi            0x0	0
rbp            0x7ffe55f82fb0	0x7ffe55f82fb0
rsp            0x7ffe55f82f60	0x7ffe55f82f60
r8             0x7f834ea08a10	140201936587280
r9             0x0	0
r10            0x7f834ea8e440	140201937134656
r11            0x0	0
r12            0x7ffe55f83210	140730340749840
r13            0x5622b7495140	94707103912256
r14            0x7ffe55f831e0	140730340749792
r15            0x7ffe55f83110	140730340749584
rip            0x5622b7095e2f	0x5622b7095e2f <get_active_class_name+31>
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) 
(gdb) p * executor_globals->current_execute_data->prev_execute_data
$22 = {
  opline = 0x7f83457c3e78, 
  call = 0x0, 
  return_value = 0x0, 
  func = 0x7f834ea80248, 
  This = {
    value = {
      lval = 140201937105280, 
      dval = 6.9268960604113991e-310, 
      counted = 0x7f834ea87180, 
      str = 0x7f834ea87180, 
      arr = 0x7f834ea87180, 
      obj = 0x7f834ea87180, 
      res = 0x7f834ea87180, 
      ref = 0x7f834ea87180, 
      ast = 0x7f834ea87180, 
      zv = 0x7f834ea87180, 
      ptr = 0x7f834ea87180, 
      ce = 0x7f834ea87180, 
      func = 0x7f834ea87180, 
      ww = {
        w1 = 1319661952, 
        w2 = 32643
      }
    }, 
    u1 = {
      v = {
        type = 8 '\b', 
        type_flags = 12 '\f', 
        const_flags = 0 '\000', 
        reserved = 2 '\002'
      }, 
      type_info = 33557512
    }, 
    u2 = {
      var_flags = 1, 
      next = 1, 
      cache_slot = 1, 
      lineno = 1, 
      num_args = 1, 
      fe_pos = 1, 
      fe_iter_idx = 1
    }
  }, 
  called_scope = 0x7f834ea7ff80, 
  prev_execute_data = 0x7f834ea1c1e0, 
  symbol_table = 0x7f834ea082a0, 
  run_time_cache = 0x7f834ea81c90, 
  literals = 0x7f83457c3d78
}
(gdb) p * executor_globals->current_execute_data->prev_execute_data->func
$23 = {
  type = 2 '\002', 
  common = {
    type = 2 '\002', 
    arg_flags = "\000\000", 
    fn_flags = 134284288, 
    function_name = 0x7f8345363650, 
    scope = 0x7f834ea7ff80, 
    prototype = 0x0, 
    num_args = 1, 
    required_num_args = 1, 
    arg_info = 0x7f83457c3f98
  }, 
  op_array = {
    type = 2 '\002', 
    arg_flags = "\000\000", 
    fn_flags = 134284288, 
    function_name = 0x7f8345363650, 
    scope = 0x7f834ea7ff80, 
    prototype = 0x0, 
    num_args = 1, 
    required_num_args = 1, 
    arg_info = 0x7f83457c3f98, 
    refcount = 0x0, 
    this_var = 128, 
    last = 13, 
    opcodes = 0x7f83457c3df8, 
    last_var = 4, 
    T = 2, 
    vars = 0x7f83457c4118, 
    last_brk_cont = 0, 
    last_try_catch = 0, 
    brk_cont_array = 0x0, 
    try_catch_array = 0x0, 
    static_variables = 0x0, 
    filename = 0x7f83457c2f80, 
    line_start = 85, 
    line_end = 101, 
    doc_comment = 0x7f83457c3fb0, 
    early_binding = 4294967295, 
    last_literal = 8, 
    literals = 0x7f83457c3d78, 
    cache_size = 40, 
    run_time_cache = 0x7f834ea81c90, 
    reserved = {0x0, 0x0, 0x0, 0x0}
  }, 
  internal_function = {
    type = 2 '\002', 
    arg_flags = "\000\000", 
    fn_flags = 134284288, 
    function_name = 0x7f8345363650, 
    scope = 0x7f834ea7ff80, 
    prototype = 0x0, 
    num_args = 1, 
    required_num_args = 1, 
    arg_info = 0x7f83457c3f98, 
    handler = 0x0, 
    module = 0xd00000080, 
    reserved = {0x7f83457c3df8, 0x200000004, 0x7f83457c4118, 0x0}
  }
}
(gdb) x/s executor_globals->current_execute_data->prev_execute_data->func->common.function_name->val
0x7f8345363668:	"registerDefaultServices"
(gdb) 
```
  
```c
ZEND_API const char *get_active_class_name(const char **space) /* {{{ */
{
	zend_function *func;

	if (!zend_is_executing()) {
		if (space) {
			*space = "";
		}
		return "";
	}

	func = EG(current_execute_data)->func;
	switch (func->type) {
		case ZEND_USER_FUNCTION:
		case ZEND_INTERNAL_FUNCTION:
		{
			zend_class_entry *ce = func->common.scope;

			if (space) {
				*space = ce ? "::" : "";
			}
			return ce ? ZSTR_VAL(ce->name) : "";
		}
		default:
			if (space) {
				*space = "";
			}
			return "";
	}
}
```

**Comment by jvoisin** [comment]
Yay, @fr33tux confirmed that this fixed the crash!

**Comment by fr33tux** [comment]
Until it did it again - @jvoisin got the new crash dump.

**Comment by jvoisin** [comment]
Apparenly, the crash is happening [here]( https://github.com/slimphp/Slim/blob/3.x/Slim/Container.php#L95 ), but I can't reproduce the crash with:

```php
<?php

require 'vendor/autoload.php';

$app = new Slim\App();

$app->get('/hello/{name}', function ($request, $response, $args) {
    return $response->getBody()->write("Hello, " . $args['name']);
});

new Slim\Container();

$app->run();

```

**Comment by jvoisin** [comment]
Sooooooo, apparently, the bug __was__ fixed, but Ansible tought that it was a great idea to redeploy the old (and thus non-fixed) version.

It's ok, I had a lot of fun debugging this mess. Not.
