### ISSUE TITLE
reproducible segfault in typo3 

### ISSUE THREAD

**Issue by kjojo** [nbs-system/snuffleupagus#157]
I've got a reproducible segfault with the following rule on a recent setup of Typo3 ( 9.1.0 ) on PHP7.2
 
```python
sp.disable_function.function_r("QueryBuilder::where$").param_r("predicates").value_r(";.*;").drop();
```

In `sp_disabled_functions.c:158`, the function `sp_is_regexp_matching` is called with a parameter `*arg_name` that seems to be `NULL`. This variable is the `is_param_matching` parameter :   `builtin_param_name`.

The function `is_param_matching` is called by `should_disable` which also take `builtin_param_name` as parameter.

The function `should_disable` seems to be called by `is_builtin_matching` in `src/sp_execute.c:41`.

## Calltrace

```nasm
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007f8c7f28f2a1 in is_param_matching (execute_data=0x7f8c89e1c860, config_node=0x55e319944de0, builtin_name=0x0, builtin_param=0x0, arg_name=0x7fff209d3508, 
    builtin_param_name=0x0, arg_value_str=0x7fff209d3510) at /home/kevin/snuffleupagus/src/sp_disabled_functions.c:158
#2  0x00007f8c7f28f942 in should_disable (execute_data=0x7f8c89e1c860, builtin_name=0x0, builtin_param=0x0, builtin_param_name=0x0)
    at /home/kevin/snuffleupagus/src/sp_disabled_functions.c:307
#3  0x00007f8c7f29044d in sp_execute_ex (execute_data=0x7f8c89e1c860) at /home/kevin/snuffleupagus/src/sp_execute.c:101
#4  0x00007f8c8f0f49ac in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#5  0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c7b0) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#6  0x00007f8c8f0f49ac in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#7  0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c710) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#8  0x00007f8c8f0f49ac in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#9  0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c5b0) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#10 0x00007f8c8f0f49ac in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#11 0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c490) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#12 0x00007f8c8f0f3e84 in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#13 0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c3c0) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#14 0x00007f8c8f0f3e84 in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#15 0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c340) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#16 0x00007f8c8f0f49ac in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#17 0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c2d0) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#18 0x00007f8c8f0f3e84 in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#19 0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c200) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#20 0x00007f8c8f0f49ac in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#21 0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c180) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#22 0x00007f8c8f0f3e84 in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#23 0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c110) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#24 0x00007f8c8f0f3e84 in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#25 0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c090) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#26 0x00007f8c8f0f3e84 in execute_ex () from /usr/lib/apache2/modules/libphp7.2.so
#27 0x00007f8c7f290529 in sp_execute_ex (execute_data=0x7f8c89e1c030) at /home/kevin/snuffleupagus/src/sp_execute.c:120
#28 0x00007f8c8f0f628e in zend_execute () from /usr/lib/apache2/modules/libphp7.2.so
#29 0x00007f8c8f044b53 in zend_execute_scripts () from /usr/lib/apache2/modules/libphp7.2.so
#30 0x00007f8c8efdfdf0 in php_execute_script () from /usr/lib/apache2/modules/libphp7.2.so
#31 0x00007f8c8f0f841a in ?? () from /usr/lib/apache2/modules/libphp7.2.so
#32 0x000055e317c48c80 in ap_run_handler (r=r@entry=0x7f8c92cce0a0) at config.c:169
#33 0x000055e317c49206 in ap_invoke_handler (r=r@entry=0x7f8c92cce0a0) at config.c:433
#34 0x000055e317c606a2 in ap_process_async_request (r=0x7f8c92cce0a0) at http_request.c:410
#35 0x000055e317c60850 in ap_process_request (r=r@entry=0x7f8c92cce0a0) at http_request.c:445
#36 0x000055e317c5c91e in ap_process_http_sync_connection (c=0x7f8c92cd2290) at http_core.c:210
#37 ap_process_http_connection (c=0x7f8c92cd2290) at http_core.c:251
#38 0x000055e317c52bf0 in ap_run_process_connection (c=c@entry=0x7f8c92cd2290) at connection.c:41
#39 0x000055e317c53000 in ap_process_connection (c=c@entry=0x7f8c92cd2290, csd=<optimized out>) at connection.c:213
#40 0x00007f8c8f6647e9 in child_main (child_num_arg=child_num_arg@entry=0x0, child_bucket=child_bucket@entry=0x0) at prefork.c:723
#41 0x00007f8c8f664a74 in make_child (s=0x7f8c92dce470, slot=slot@entry=0x0, bucket=0x0) at prefork.c:824
#42 0x00007f8c8f664aeb in startup_children (number_to_start=0x1) at prefork.c:843
#43 0x00007f8c8f665ac7 in prefork_run (_pconf=<optimized out>, plog=0x7f8c92dc9028, s=0x7f8c92dce470) at prefork.c:1010
#44 0x000055e317c2b46e in ap_run_mpm (pconf=0x7f8c92dfc028, plog=0x7f8c92dc9028, s=0x7f8c92dce470) at mpm_common.c:94
#45 0x000055e317c24400 in main (argc=argc@entry=0x3, argv=argv@entry=0x7fff209d6b18) at main.c:777
#46 0x00007f8c91f4e830 in __libc_start_main (main=0x55e317c23a50 <main>, argc=0x3, argv=0x7fff209d6b18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fff209d6b08) at ../csu/libc-start.c:291
#47 0x000055e317c244f9 in _start ()
```

## Context

```nasm
[----------------------------------registers-----------------------------------]
RAX: 0x600000078 
RBX: 0x7f8c8f453140 --> 0x0 
RCX: 0x78 ('x')
RDX: 0x600000078 
RSI: 0x3b (';')
RDI: 0x600000078 
RBP: 0x7fff209d34c0 --> 0x7fff209d35a0 --> 0x7fff209d35d0 --> 0x7f8c89e1c860 --> 0x7f8c768dabb8 --> 0x7f8c8f0f0a25 (<execute_ex+11605>:	call   0x7f8c8f0ec000)
RSP: 0x7fff209d3448 --> 0x7f8c7f28f2a1 (<is_param_matching+537>:	mov    rdx,rax)
RIP: 0x7f8c91fb9746 (<strlen+38>:	movdqu xmm4,XMMWORD PTR [rax])
R8 : 0x55555556 ('VUUU')
R9 : 0x0 
R10: 0x0 
R11: 0x7fff209d3390 --> 0xffffffffffffffff 
R12: 0x7f8c89e01008 --> 0x55e319766cd0 --> 0x10000000001 
R13: 0x7f8c74e5e178 --> 0xc901010000000002 
R14: 0x7f8c89e1c7b0 --> 0x7f8c769ba3d8 --> 0x7f8c8f0f0c0b (<execute_ex+12091>:	mov    rbp,QWORD PTR [r14+0x8])
R15: 0x7f8c769ba3d8 --> 0x7f8c8f0f0c0b (<execute_ex+12091>:	mov    rbp,QWORD PTR [r14+0x8])
EFLAGS: 0x10297 (CARRY PARITY ADJUST zero SIGN trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7f8c91fb9736 <strlen+22>:	and    rcx,0xfff
   0x7f8c91fb973d <strlen+29>:	cmp    rcx,0xfcf
   0x7f8c91fb9744 <strlen+36>:	ja     0x7f8c91fb97b0 <strlen+144>
=> 0x7f8c91fb9746 <strlen+38>:	movdqu xmm4,XMMWORD PTR [rax]
   0x7f8c91fb974a <strlen+42>:	pcmpeqb xmm4,xmm0
   0x7f8c91fb974e <strlen+46>:	pmovmskb edx,xmm4
   0x7f8c91fb9752 <strlen+50>:	test   edx,edx
   0x7f8c91fb9754 <strlen+52>:	je     0x7f8c91fb975a <strlen+58>
[------------------------------------stack-------------------------------------]
0000| 0x7fff209d3448 --> 0x7f8c7f28f2a1 (<is_param_matching+537>:	mov    rdx,rax)
0008| 0x7fff209d3450 --> 0x0 
0016| 0x7fff209d3458 --> 0x7fff209d3508 --> 0x600000078 
0024| 0x7fff209d3460 --> 0x0 
0032| 0x7fff209d3468 --> 0x0 
0040| 0x7fff209d3470 --> 0x55e319944de0 --> 0x7f8c89e0d2a0 --> 0x7f8c89e0d328 --> 0x7f8c89e0d000 --> 0x2 
0048| 0x7fff209d3478 --> 0x7f8c89e1c860 --> 0x7f8c768dabb8 --> 0x7f8c8f0f0a25 (<execute_ex+11605>:	call   0x7f8c8f0ec000)
0056| 0x7fff209d3480 --> 0x1007fff209d34d0 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
```

**Comment by jvoisin** [comment]
I can reproduce it.
