### ISSUE TITLE
SIGSEGV in arrays handling

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/snuffleupagus#59]
Drop the follwing file in your `src/tests` folder:

```php
--TEST--
Disable functions - match on an array value buried in several levels
--SKIPIF--
<?php if (!extension_loaded("snuffleupagus")) die "skip"; ?>
--INI--
sp.configuration_file={PWD}/config/config_disabled_functions_param_array.ini
--FILE--
<?php
function foo($arr) {
	 echo $arr["a"]."\n";
}
$a=Array("test2"=>Array("pof"=>"pif", "foo"=>Array(Array("nope"=>"Nupe"), "lol"=>"bbb")), "a"=>"cccc");
foo($a);

$a=Array("test2"=>Array("foo"=>Array("lol"=>"aaa")), "a"=>"dddd");
foo($a);
?>
--EXPECTF--
cccc
[snuffleupagus][0.0.0.0][disabled_function][drop] The call to the function 'foo' in %a/tests/disabled_functions_param_array_several_levels.php:3 has been disabled, because its argument 'arr' content (Array) matched the rule '4'.

```

```c
gdb-peda$ r
Starting program: /usr/bin/php7.0 -n -c /home/jvoisin/Dev/snuffleupagus/src/tmp-php.ini -d output_handler= -d open_basedir= -d safe_mode=0 -d disable_functions= -d output_buffering=Off -d error_reporting=32767 -d display_errors=1 -d display_startup_errors=1 -d log_errors=0 -d html_errors=0 -d track_errors=1 -d report_memleaks=1 -d report_zend_debug=0 -d docref_root= -d docref_ext=.html -d error_prepend_string= -d error_append_string= -d auto_prepend_file= -d auto_append_file= -d ignore_repeated_errors=0 -d precision=14 -d memory_limit=128M -d log_errors_max_len=0 -d opcache.fast_shutdown=0 -d opcache.file_update_protection=0 -d extension_dir=/home/jvoisin/Dev/snuffleupagus/src/modules/ -d extension=snuffleupagus.so -d session.auto_start=0 -d zlib.output_compression=Off -d sp.configuration_file=/home/jvoisin/Dev/snuffleupagus/src/tests/config/config_disabled_functions_param_array.ini -f /home/jvoisin/Dev/snuffleupagus/src/tests/disabled_functions_param_array_several_levels.php
warning: the debug information found in "/lib64/ld-2.24.so" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.

 [----------------------------------registers-----------------------------------]
RAX: 0x18 
RBX: 0x7ffff38140e0 --> 0x7ffff3877160 --> 0x55555581c900 (sub    rsp,0x8)
RCX: 0x0 
RDX: 0x0 
RSI: 0x7ffff0e72010 --> 0xe4006c6f6c 
RDI: 0x18 
RBP: 0x7fffffffa0a0 --> 0x7fffffffa120 --> 0x7fffffffa1a0 --> 0x7fffffffa2b0 --> 0x7fffffffa2d0 --> 0x7ffff3804000 (--> ...)
RSP: 0x7fffffffa028 --> 0x7ffff2d6328e (<sp_match_array_key_recurse+207>:	test   eax,eax)
RIP: 0x7ffff64930da (<__strcmp_sse2_unaligned+26>:	movdqu xmm1,XMMWORD PTR [rdi])
R8 : 0x7ffff385eba0 --> 0x0 
R9 : 0xce 
R10: 0xd2 
R11: 0x7ffff2d631bf (<sp_match_array_key_recurse>:	push   rbp)
R12: 0x7ffff38040e8 --> 0x800000000000002 
R13: 0x555555ba6740 --> 0x0 
R14: 0x7ffff3814030 --> 0x7ffff385f0c0 --> 0x55555583cda0 (push   r13)
R15: 0x7ffff385f0c0 --> 0x55555583cda0 (push   r13)
EFLAGS: 0x10283 (CARRY parity adjust zero SIGN trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff64930ca <__strcmp_sse2_unaligned+10>:	and    eax,0xfff
   0x7ffff64930cf <__strcmp_sse2_unaligned+15>:	cmp    eax,0xfc0
   0x7ffff64930d4 <__strcmp_sse2_unaligned+20>:	jg     0x7ffff6493352 <__strcmp_sse2_unaligned+658>
=> 0x7ffff64930da <__strcmp_sse2_unaligned+26>:	movdqu xmm1,XMMWORD PTR [rdi]
   0x7ffff64930de <__strcmp_sse2_unaligned+30>:	movdqu xmm0,XMMWORD PTR [rsi]
   0x7ffff64930e2 <__strcmp_sse2_unaligned+34>:	pcmpeqb xmm0,xmm1
   0x7ffff64930e6 <__strcmp_sse2_unaligned+38>:	pminub xmm0,xmm1
   0x7ffff64930ea <__strcmp_sse2_unaligned+42>:	pxor   xmm1,xmm1
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffa028 --> 0x7ffff2d6328e (<sp_match_array_key_recurse+207>:	test   eax,eax)
0008| 0x7fffffffa030 --> 0x0 
0016| 0x7fffffffa038 --> 0x7ffff0e78010 --> 0x616161 ('aaa')
0024| 0x7fffffffa040 --> 0x7ffff0e71010 --> 0x0 
0032| 0x7fffffffa048 --> 0x7ffff385e900 --> 0x7ffff3857428 --> 0x700000001 
0040| 0x7fffffffa050 --> 0x7ffff385ea20 --> 0x7ffff38573f0 --> 0x700000001 
0048| 0x7fffffffa058 --> 0x7ffff0e71010 --> 0x0 
0056| 0x7fffffffa060 --> 0x7ffff385ea60 --> 0x0 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
gdb-peda$ bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x00007ffff2d6328e in sp_match_array_key_recurse (arr=0x7ffff385e900, keys=0x7ffff0e71010, to_match=0x7ffff0e78010 "aaa", rx=0x0) at /home/jvoisin/Dev/snuffleupagus/src/sp_utils.c:343
#2  0x00007ffff2d632ad in sp_match_array_key_recurse (arr=0x7ffff385f1a0, keys=0x7ffff0e73010, to_match=0x7ffff0e78010 "aaa", rx=0x0) at /home/jvoisin/Dev/snuffleupagus/src/sp_utils.c:344
#3  0x00007ffff2d632ad in sp_match_array_key_recurse (arr=0x7ffff3814140, keys=0x7ffff0e76010, to_match=0x7ffff0e78010 "aaa", rx=0x0) at /home/jvoisin/Dev/snuffleupagus/src/sp_utils.c:344
#4  0x00007ffff2d648f8 in should_disable (execute_data=0x7ffff38140e0) at /home/jvoisin/Dev/snuffleupagus/src/sp_disabled_functions.c:232
#5  0x00007ffff2d6536b in sp_execute_ex (execute_data=0x7ffff38140e0) at /home/jvoisin/Dev/snuffleupagus/src/sp_execute.c:59
#6  0x000055555583d13d in ?? ()
#7  0x00005555557f7ddb in execute_ex ()
#8  0x00007ffff2d653c7 in sp_execute_ex (execute_data=0x7ffff3814030) at /home/jvoisin/Dev/snuffleupagus/src/sp_execute.c:74
#9  0x000055555584c617 in zend_execute ()
#10 0x00005555557b7203 in zend_execute_scripts ()
#11 0x00005555557560b0 in php_execute_script ()
#12 0x000055555584e2d0 in ?? ()
#13 0x000055555563885e in main ()
#14 0x00007ffff64123f1 in __libc_start_main (main=0x5555556383f0 <main>, argc=0x42, argv=0x7fffffffdd38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd28) at ../csu/libc-start.c:291
#15 0x00005555556389aa in _start ()
gdb-peda$ p key
$1 = 0x0
gdb-peda$
```

It looks like there is a NULL-deref in the `sp_match_array_key_recurse` due to an array value without a key.

It would be nice to add a lot of different testcases for every different form of array in the commit fixing this issue ♥

**Comment by jvoisin** [comment]
Done in e7f541396715ee2895abcf73044b91ae9b746201
